# Generated by Django 4.2.21 on 2025-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyvalleycottages', '0002_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
