# Generated by Django 4.2.21 on 2025-05-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyvalleycottages', '0003_reservation_guest_notes_reservation_host_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
    ]
